apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka-local
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka"
  replicas: 1
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:      
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
