apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka-local
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: plaintext
  type: ClusterIP
  selector:
    app: kafka
