{{- if .Values.deploymentEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: local
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      namespace: local
    spec:
      containers:
        - name: {{ .Values.name }}
          image: mateusalxd/camel-kafka-consumer
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKERS
              value: kafka-0-service.kafka.svc.cluster.local:9092,kafka-0-service.kafka.svc.cluster.local:9093
            - name: KAFKA_CONSUMER_GROUP
              value: deployment-consumer-group
            - name: KAFKA_TOPIC
              value: topic1
            - name: CHECK_INTERVAL_MS
              value: "60000"
            - name: MAXIMUM_IDLE_TIME_MS
              value: "300000"
{{- end }}